on:
  release:
    branches:
      - development

jobs:
  test-pw-workflow:
    runs-on: ubuntu-latest
    name: test-pw-workflow-beluga
    steps:
      - name: run-workflow-beluga
        id: run-beluga
        uses: parallelworks/test-workflow-action@v5
        with:
          pw-user-host: 'beluga.parallel.works'
          pw-api-key: ${{ secrets.USERDEMO_BELUGA_API_KEY }}
          pw-user: 'User.Demo'
          resource-pool-names: 'gcpslurmv2basic'
          workflow-name: 'singlecluster_parsl_demo'
          workflow-parameters: '{"inputs": {"name": "PW_USER"},"cicd": {"merge": "true","branch": "development"}}'
